### ISSUE TITLE
GCC Error - Thrown on Windows 10 machine with python

### ISSUE THREAD

**Issue by sajackson314314** [tyson-swetnam/rillgen2d#18]
```
The system cannot find the path specified.
rillgen2d.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 #include<stdio.h>
 ^
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\sajac\miniconda3\envs\rillgen2d\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\sajac\Downloads\rillgen2d-main\rillgen2d.py", line 251, in saveimageastxt
    self.client_socket.send(subprocess.check_output(cmd, shell=True) + ('\n').encode('utf-8'))
  File "C:\Users\sajac\miniconda3\envs\rillgen2d\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\sajac\miniconda3\envs\rillgen2d\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'gcc -Wall -shared -fPIC rillgen2d.c -o rillgen.so' returned non-zero exit status 1.
```

**Comment by tyson-swetnam** [comment]
fixed: running with Cygwin, removed `-fPIC` and changed `rillgen.so` to `rillgen2d.exe`
